name: Label PRs

on:
  - pull_request
  - issues

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: srvaroa/labeler@master
        with:
          config_path: .github/labeler.yml
          use_local_config: false
          fail_on_error: false
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
